### ISSUE TITLE
how to solve this training error?

### ISSUE THREAD

**Issue by InvincibleZZH** [zaixizhang/FLAG#3]
Indexing:   1%|█                                                                            | 2200/166398 [00:20<25:42, 106.46it/s]
Traceback (most recent call last):
  File "train.py", line 63, in <module>
    dataset, subsets = get_dataset(config=config.dataset, transform=transform, )
  File "/data/zhouzihan/FLAG-main/utils/datasets/__init__.py", line 11, in get_dataset
    dataset = PocketLigandPairDataset(root, *args, **kwargs)
  File "/data/zhouzihan/FLAG-main/utils/datasets/pl.py", line 64, in __init__
    self._precompute_name2id()
  File "/data/zhouzihan/FLAG-main/utils/datasets/pl.py", line 132, in _precompute_name2id
    data = self.__getitem__(i)
  File "/data/zhouzihan/FLAG-main/utils/datasets/pl.py", line 153, in __getitem__
    data = self.transform(data)
  File "/home/ahmu/ENTER/envs/flag_env/lib/python3.8/site-packages/torch_geometric/transforms/compose.py", line 24, in __call__
    data = transform(data)
  File "/data/zhouzihan/FLAG-main/utils/transforms.py", line 471, in __call__
    bfs_perm, bfs_focal = self.get_bfs_perm_motif(data['moltree'], self.vocab)
  File "/data/zhouzihan/FLAG-main/utils/transforms.py", line 449, in get_bfs_perm_motif
    node.wid = vocab.get_index(node.smiles)
  File "/data/zhouzihan/FLAG-main/utils/mol_tree.py", line 24, in get_index
    return self.vmap[smiles]
KeyError: 'C1CC2CCC(O1)O2'

**Comment by Jiangyuliang0813** [comment]
I have the same problem too

**Comment by zaixizhang** [comment]
Hi, thanks for your feedback!
We have updated the corresponding codes and the indexing error is solved.
